name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TAG: extensionbuilder:$(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: ${{ TAG }}
    - name: Pack Extension
      run: docker run -v .:/app $TAG
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: 'extension'
        path: './scr.crx'
      
